# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: ruby_extensions 1.6.0 ruby lib

Gem::Specification.new do |s|
  s.name = "ruby_extensions"
  s.version = "1.11.1"

  s.require_paths = ['lib']
  s.authors = ['Zachary Powell']
  s.date = '2014-11-18'
  s.email = 'zach@babelian.net'
  s.extra_rdoc_files = [
    'LICENSE',
    'README.md'
  ]
  s.files = Dir.glob('{lib}/**/*')
  s.homepage = 'http://github.com/babelian/ruby_extensions'
  s.rubygems_version = '3.0.1'
  s.summary = 'Extensions for Ruby core classes'

  s.add_development_dependency 'bump'
  s.add_development_dependency 'rspec', '3.0.0'
end

